// flow-typed signature: 522eb1f3ff1b6ce14bd8aff81458e169
// flow-typed version: <<STUB>>/eslint-config-react-app_v^0.5.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-react-app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-react-app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-react-app/index' {
  declare module.exports: $Exports<'eslint-config-react-app'>;
}
declare module 'eslint-config-react-app/index.js' {
  declare module.exports: $Exports<'eslint-config-react-app'>;
}
